name: CD - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Image and Run
        env:
          REGISTRY_IP: ${{ secrets.REGISTRY_IP }}
        run: |
          # 1. Bajamos la imagen fresca de la Instancia 2 (Usando V2)
          docker compose pull
          # 2. Reiniciamos el contenedor con la nueva imagen (Usando V2)
          docker compose up -d